\i sql_bits/aggregate.sql
\i sql_bits/bit.sql
\i sql_bits/casts.sql
\i sql_bits/controlflow.sql
\i sql_bits/datetime.sql
\i sql_bits/information.sql
\i sql_bits/mathematical.sql
\i sql_bits/misc.sql
\i sql_bits/operators.sql
\i sql_bits/string.sql
